# Generated by Django 5.2.17 on 2026-09-18 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_self_assessment_result_permissions'),
        ('rounds', '0004_collection_data_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_code', models.SlugField(max_length=80)),
                ('label_th', models.CharField(max_length=200)),
                ('label_en', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('realm', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=8)),
                ('expires_at', models.DateTimeField()),
                ('workload', models.BooleanField(default=False)),
                ('prize', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rounds.roundinstrument')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ParticipationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('revoked', models.BooleanField(default=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='participation.receiptpolicy')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VerifierClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=80)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('realm', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReceiptRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('workload', 'Workload'), ('prize', 'Prize')], max_length=12)),
                ('idempotency_hash', models.CharField(editable=False, max_length=64)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='participation.participationreceipt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participation.verifierclient')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VerifierGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('workload', 'Workload'), ('prize', 'Prize')], max_length=12)),
                ('can_redeem', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participation.verifierclient')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participation.receiptpolicy')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='receiptpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('realm__in', ['test', 'live'])), name='participation_policy_realm'),
        ),
        migrations.AddConstraint(
            model_name='receiptpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('workload', True), ('prize', True), _connector='OR'), name='participation_policy_purpose'),
        ),
        migrations.AddConstraint(
            model_name='receiptpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='participation_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='verifierclient',
            constraint=models.UniqueConstraint(fields=('scope', 'name'), name='participation_client_name'),
        ),
        migrations.AddConstraint(
            model_name='verifierclient',
            constraint=models.CheckConstraint(condition=models.Q(('realm__in', ['test', 'live'])), name='participation_client_realm'),
        ),
        migrations.AddConstraint(
            model_name='receiptredemption',
            constraint=models.UniqueConstraint(fields=('receipt', 'purpose'), name='participation_once_per_purpose'),
        ),
        migrations.AddConstraint(
            model_name='receiptredemption',
            constraint=models.UniqueConstraint(fields=('client', 'idempotency_hash'), name='participation_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='receiptredemption',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['workload', 'prize'])), name='participation_redemption_purpose'),
        ),
        migrations.AddConstraint(
            model_name='verifiergrant',
            constraint=models.UniqueConstraint(fields=('client', 'policy', 'purpose'), name='participation_client_grant'),
        ),
        migrations.AddConstraint(
            model_name='verifiergrant',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['workload', 'prize'])), name='participation_grant_purpose'),
        ),
    ]
