# Generated by Django 5.2.17 on 2026-09-18 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0002_store_guards'),
        ('rounds', '0004_collection_data_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('spent', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(default=False)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.roundinstrument')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccessPool',
            fields=[
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='rounds.roundinstrument')),
                ('capacity', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='participation_pool_capacity')],
            },
        ),
        migrations.CreateModel(
            name='AccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participation.accesspass')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
