# Generated by Django 5.2.17 on 2026-09-19 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0005_aggregate_access_context'),
        ('rounds', '0004_collection_data_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCollection',
            fields=[
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='public_collection', serialize=False, to='rounds.roundinstrument')),
                ('contract_version', models.CharField(default='2026-09-19', max_length=24)),
                ('level', models.CharField(blank=True, max_length=16)),
                ('programme', models.CharField(blank=True, max_length=40)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PublicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('year', models.CharField(blank=True, max_length=8)),
                ('spent', models.BooleanField(default=False)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.roundinstrument')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
