# Generated by Django 5.2.17 on 2026-09-20 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_self_assessment_result_permissions'),
        ('participation', '0008_public_session_clock'),
        ('rounds', '0004_collection_data_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='participation.assessmentbatch')),
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch_item', to='rounds.roundinstrument')),
            ],
        ),
    ]
