from apps.governance import refresh_web
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from apps.accounts import web, account_setup, backoffice
from apps.catalog import web as catalog_web, management_web as catalog_manage, preview, group_web
from apps.rounds import web as round_web
from apps.selfassessments import web as self_web, api as self_api
from apps.selfassessments import operator_web

from apps.surveys import web as survey_web, operator as survey_operator
from apps.participation import web as participation
from apps.participation import presentation as participation_pages
from apps.participation import operator as participation_operator
from apps.participation import setup as participation_setup
from apps.participation import results as participation_results
from apps.participation import public_web
from apps.participation import public_setup
from apps.participation import batches

from apps.calculations import dashboard, demo_dashboard, activity_web, comparisons, visualization, quality
from apps.manuals import views as manuals
from apps.manuals import operations_web
from apps.leadership import web as leadership
from apps.governance import web as governance
from apps.catalog import alignment_web

urlpatterns = [
    path('survey/public/', public_web.home, name='public-assessments'),
    path('workspace/<uuid:scope_id>/assessments/new/', batches.setup, name='assessment-batch-new'),
    path('workspace/<uuid:scope_id>/assessments/<uuid:batch_id>/', batches.manage, name='assessment-batch-manage'),
    path('survey/public/choices/', public_web.choices, name='public-assessment-choices'),
    path('survey/public/start/', public_web.start, name='public-assessment-start'),
    path('survey/public/form/', public_web.form, name='public-assessment-form'),
    path('workspace/<uuid:scope_id>/surveys/<uuid:selected_id>/public/new/', public_setup.setup, name='public-assessment-setup'),
    path('workspace/<uuid:scope_id>/surveys/<uuid:selected_id>/public/', public_setup.manage, name='public-assessment-manage'),
    path('survey/entry/', participation_pages.entry, name='participation-entry'),
    path('survey/participation/enter/', participation.enter, name='participation-enter'),
    path('survey/participation/form/', participation_pages.form, name='participation-form'),
    path('survey/participation/receipt/', participation_pages.holder, name='participation-holder'),
    path('survey/participation/qr/', participation.qr, name='participation-qr'),
    path('survey/participation/download/', participation.download, name='participation-download'),
    path('survey/participation/prepare/', participation.prepare, name='participation-prepare'),
    path('survey/participation/submit/', participation.submit, name='participation-submit'),
    path('survey/participation/status/', participation.status, name='participation-status'),
    path('participation/v1/verify/', participation.verify, name='participation-verify'),
    path('participation/v1/redeem/', participation.redeem, name='participation-redeem'),
    path('workspace/<uuid:scope_id>/surveys/<uuid:selected_id>/invitations/', participation_operator.manage, name='participation-manage'),
    path('workspace/<uuid:scope_id>/surveys/<uuid:selected_id>/new-test-collection/', participation_setup.setup, name='participation-setup'),
    path('workspace/<uuid:scope_id>/surveys/<uuid:selected_id>/results/', participation_results.overview, name='participation-results'),
    path('workspace/<uuid:scope_id>/refresh/',refresh_web.overview,name='workspace-refresh'),
    path("workspace/<uuid:scope_id>/indicators/", alignment_web.overview, name="indicator-alignment"),
    path("workspace/<uuid:scope_id>/indicators/export/", alignment_web.overview, {"export":True}, name="indicator-alignment-export"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/readable/", alignment_web.prepare_wording, name="indicator-wording-prepare"),
    path("workspace/<uuid:scope_id>/annual-policy/", governance.annual_policy, name="annual-policy"),
    path("workspace/<uuid:scope_id>/anonymous-f05/", governance.prepare_f05, name="anonymous-f05-prepare"),
    path('register/', governance.register, name='access-register'),
    path('register/<uuid:scope_id>/', governance.register, name='access-register-scope'),
    path('account/verify/', governance.code, {'kind':'verify'}, name='access-verify'),
    path('account/activate/', governance.code, {'kind':'activate'}, name='access-activate'),
    path('workspace/<uuid:scope_id>/access/', governance.requests, name='access-requests'),
    path('workspace/<uuid:scope_id>/access/policy/', governance.policy, name='access-policy'),
    path('workspace/<uuid:scope_id>/access/new/', governance.admin_create, name='access-admin-create'),
    path('workspace/<uuid:scope_id>/access/<uuid:pk>/', governance.decision, name='access-decision'),
    path('workspace/<uuid:scope_id>/notifications/', governance.notifications, name='notifications'),
    path('workspace/<uuid:scope_id>/f04/', leadership.overview, name='f04-register'),
    path('workspace/<uuid:scope_id>/f04/masters/<str:kind>/', leadership.master, name='f04-master'),
    path('workspace/<uuid:scope_id>/f04/masters/<str:kind>/<uuid:pk>/', leadership.master, name='f04-master-edit'),
    path('workspace/<uuid:scope_id>/f04/years/<uuid:plan_id>/', leadership.plan, name='f04-plan'),
    path('workspace/<uuid:scope_id>/f04/years/<uuid:plan_id>/new/', leadership.target_edit, name='f04-target-new'),
    path('workspace/<uuid:scope_id>/f04/years/<uuid:plan_id>/copy/', leadership.copy, name='f04-copy'),
    path('workspace/<uuid:scope_id>/f04/years/<uuid:plan_id>/generate/', leadership.generate, name='f04-generate'),
    path('workspace/<uuid:scope_id>/f04/years/<uuid:plan_id>/edit/<uuid:pk>/', leadership.target_edit, name='f04-target-edit'),
    path('workspace/<uuid:scope_id>/f04/targets/<uuid:pk>/', leadership.target, name='f04-target'),
    path('workspace/<uuid:scope_id>/f04/targets/<uuid:pk>/<str:action>/', leadership.action, name='f04-action'),
    path('workspace/<uuid:scope_id>/f04/targets/<uuid:pk>/remove/<uuid:eligible_id>/', leadership.action, {'action':'remove'}, name='f04-eligibility-remove'),
    path('manuals/operations/<str:key>/', operations_web.guide, name='manuals-operations'),
    path('manuals/operations/<str:key>/download/', operations_web.download, name='manuals-operations-download'),
    path('manuals/', manuals.index, name='manuals-home'),
    path('manuals/current/',manuals.current,name='manuals-current'),
    path('manuals/<slug:slug>/', manuals.detail, name='manuals-detail'),
    path('manuals/<slug:slug>/download/', manuals.download, name='manuals-download'),
    path('workspace/<uuid:scope_id>/quality/', quality.overview, name='quality-home'),
    path('workspace/<uuid:scope_id>/quality/export/', quality.overview, {'export':True}, name='quality-export'),
    path('workspace/<uuid:scope_id>/visualization/', visualization.overview, name='visualization-home'),
    path('workspace/<uuid:scope_id>/visualization/endlessloop/', visualization.overview, {'mode':'endlessloop'}, name='visualization-endlessloop'),
    path('workspace/<uuid:scope_id>/visualization/finereport/', visualization.overview, {'mode':'finereport'}, name='visualization-finereport'),
    path('workspace/<uuid:scope_id>/visualization/export/', visualization.overview, {'export':True}, name='visualization-export'),
    path('workspace/<uuid:scope_id>/groups/', group_web.overview, name='group-register'),
    path('workspace/<uuid:scope_id>/assessments/preview/', preview.overview, name='assessment-preview-list'),
    path('workspace/<uuid:scope_id>/assessments/preview/<uuid:version_id>/<str:group_code>/', preview.detail, name='assessment-preview'),
    path('account/password/', auth_views.PasswordChangeView.as_view(template_name='portal/password_change.html', success_url='/account/password/done/'), name='password-change'),
    path('account/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='portal/password_done.html'), name='password-change-done'),
    path('workspace/<uuid:scope_id>/administration/', backoffice.overview, name='backoffice-home'),
    path('workspace/<uuid:scope_id>/administration/settings/', backoffice.settings, name='backoffice-settings'),
    path('workspace/<uuid:scope_id>/administration/audit/', backoffice.audit, name='backoffice-audit'),
    path('workspace/<uuid:scope_id>/insights/compare/', comparisons.overview, name='insights-compare'),
    path('workspace/<uuid:scope_id>/activities/', activity_web.overview, name='activity-list'),
    path('workspace/<uuid:scope_id>/activities/new/', activity_web.create, name='activity-new'),
    path('workspace/<uuid:scope_id>/activities/<uuid:selected_id>/', activity_web.collection, name='activity-collection'),
    path('workspace/<uuid:scope_id>/activities/<uuid:selected_id>/new/', activity_web.entry, name='activity-entry-new'),
    path('workspace/<uuid:scope_id>/activities/<uuid:selected_id>/<uuid:record_id>/', activity_web.entry, name='activity-entry'),
    path('workspace/<uuid:scope_id>/insights/demo/', demo_dashboard.overview, name='insights-demo'),
    path('workspace/<uuid:scope_id>/insights/demo/export/', demo_dashboard.overview, {'export':True}, name='insights-demo-export'),
    path('workspace/<uuid:scope_id>/insights/', dashboard.overview, name='insights-list'),
    path('workspace/<uuid:scope_id>/insights/<uuid:run_id>/', dashboard.detail, name='insights-detail'),
    path('workspace/<uuid:scope_id>/insights/<uuid:run_id>/export/', dashboard.detail, {'export':True}, name='insights-export'),
    path('survey/', survey_web.access, name='survey-access'),
    path('survey/answer/', survey_web.answer, name='survey-answer'),
    path('workspace/<uuid:scope_id>/surveys/', survey_operator.overview, name='survey-list'),
    path('workspace/<uuid:scope_id>/surveys/new/', survey_operator.create, name='survey-new'),
    path('workspace/<uuid:scope_id>/surveys/<uuid:selected_id>/', survey_operator.collection, name='survey-collection'),
    path('workspace/<uuid:scope_id>/surveys/<uuid:selected_id>/invite/<uuid:member_id>/', survey_operator.invite, name='survey-invite'),
    path('workspace/<uuid:scope_id>/surveys/<uuid:selected_id>/calculate/', survey_operator.calculate, name='survey-calculate'),
    path("", web.home, name="home"),
    path("login/", auth_views.LoginView.as_view(template_name="portal/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("language/", web.language, name="portal-language"),
    path("workspace/", web.workspace, name="workspace"),
    path("workspace/<uuid:scope_id>/members/new/", governance.admin_create, name="portal-account-new"),
    path("workspace/<uuid:scope_id>/members/", web.members, name="portal-members"),
    path("workspace/<uuid:scope_id>/grants/<uuid:assignment_id>/revoke/", web.revoke, name="portal-revoke"),
    path("workspace/<uuid:scope_id>/catalog/", catalog_web.catalog, name="portal-catalog"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/", catalog_web.version_detail, name="portal-catalog-detail"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/edit/", catalog_manage.version_edit, name="portal-catalog-edit"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/questions/new/", catalog_manage.question_edit, name="portal-catalog-question-new"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/questions/<uuid:question_id>/edit/", catalog_manage.question_edit, name="portal-catalog-question-edit"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/questions/<uuid:question_id>/delete/", catalog_manage.question_delete, name="portal-catalog-question-delete"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/clone/", catalog_manage.clone, name="portal-catalog-clone"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/prepare/", catalog_manage.prepare, name="portal-catalog-prepare"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/review/<uuid:bundle_id>/", catalog_manage.review, name="portal-catalog-review"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/translation/<uuid:entry_id>/", catalog_manage.translation_edit, name="portal-catalog-translation"),
    path("workspace/<uuid:scope_id>/catalog/<uuid:version_id>/publish/", catalog_manage.publish, name="portal-catalog-publish"),
    path("workspace/<uuid:scope_id>/rounds/", round_web.overview, name="round-list"),
    path("workspace/<uuid:scope_id>/rounds/period/new/", round_web.period_create, name="round-period-new"),
    path("workspace/<uuid:scope_id>/rounds/new/", round_web.edit, name="round-new"),
    path("workspace/<uuid:scope_id>/rounds/<uuid:round_id>/", round_web.detail, name="round-detail"),
    path("workspace/<uuid:scope_id>/rounds/<uuid:round_id>/edit/", round_web.edit, name="round-edit"),
    path("workspace/<uuid:scope_id>/rounds/<uuid:round_id>/population/", round_web.population_edit, name="round-population"),
    path("workspace/<uuid:scope_id>/rounds/<uuid:round_id>/members/new/", round_web.member_edit, name="round-member-new"),
    path("workspace/<uuid:scope_id>/rounds/<uuid:round_id>/members/<uuid:member_id>/edit/", round_web.member_edit, name="round-member-edit"),
    path("workspace/<uuid:scope_id>/rounds/<uuid:round_id>/members/<uuid:member_id>/delete/", round_web.action, {"action": "remove"}, name="round-member-delete"),
    path("workspace/<uuid:scope_id>/rounds/<uuid:round_id>/action/<str:action>/", round_web.action, name="round-action"),
    path("workspace/self-assessments/", self_web.mine, name="self-assessment-list"),
    path("workspace/self-assessments/<uuid:assignment_id>/", self_web.detail, name="self-assessment-detail"),
    path("workspace/<uuid:scope_id>/collection/", operator_web.overview, name="operator-list"),
    path("workspace/<uuid:scope_id>/collection/<uuid:selected_id>/", operator_web.collection, name="operator-collection"),
    path("workspace/<uuid:scope_id>/collection/<uuid:selected_id>/roster/", operator_web.roster, name="operator-roster"),
    path("workspace/<uuid:scope_id>/collection/<uuid:selected_id>/assign/<uuid:member_id>/", operator_web.assign, name="operator-assign"),
    path("workspace/<uuid:scope_id>/collection/<uuid:selected_id>/calculate/", operator_web.calculate, name="operator-calculate"),
    path("workspace/<uuid:scope_id>/results/<uuid:run_id>/", operator_web.result, name="operator-run"),
    path("api/v1/me/self-assessments/", self_api.mine),
    path("api/v1/me/self-assessments/<uuid:assignment_id>/", self_api.own_schema),
    path("api/v1/me/self-assessments/<uuid:assignment_id>/draft/", self_api.draft),
    path("api/v1/me/self-assessments/<uuid:assignment_id>/submit/", self_api.submit),
    path("api/v1/self-assessment-assignments/", self_api.assign),
    path("api/v1/round-instruments/<uuid:round_instrument_id>/calculate/", self_api.calculate),
    path("api/v1/calculation-runs/<uuid:run_id>/review-request/", self_api.review_request),
    path("api/v1/calculation-runs/<uuid:run_id>/review/", self_api.review_packet),
    path("api/v1/calculation-runs/<uuid:run_id>/decision/", self_api.review_decision),
    path("admin/", admin.site.urls),
]
