# Generated by Django 5.2.17 on 2026-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_policy_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='privacy_contact_snapshot',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='privacy_notice_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
