'use strict';
(() => {
 const data=JSON.parse(document.getElementById('preview-data').textContent),answers=new Map();
 let lang=data.runtime?.locale==='en'?'en':'th',current=0,completed=false;
 const connection=typeof F01Connected==='undefined'?null:F01Connected.create(data,{language:()=>lang,onIssued:()=>{completed=true;show(9,true);}});
 const $=id=>document.getElementById(id), t=(th,en)=>lang==='th'?th:en;
 const text=q=>lang==='th'?q.text:q.text_en, label=o=>lang==='th'?o.label:o.label_en, fixed=q=>lang==='th'?q.fixed:q.fixed_en;
 const make=(tag,txt,cls)=>{const n=document.createElement(tag);if(txt!==undefined)n.textContent=txt;if(cls)n.className=cls;return n;};
 const key=q=>q.id.split('-')[1][0], visible=q=>F01Validation.visible(q,answers), valid=q=>F01Validation.valid(q,answers.get(q.id));
 const definitions=[
 ['P','ข้อมูลประกอบการประเมิน','Your context','กลุ่มและหลักสูตรกำหนดจากคำเชิญ เลือกชั้นปีของท่าน','Your invitation sets your group and programme. Select your year of study.','◎'],
 ['S','ความพึงพอใจ','Satisfaction','เลือก 1–5 ตามประสบการณ์ หรือใช้ตัวเลือกไม่มีประสบการณ์ / ยังประเมินไม่ได้','Choose 1–5 based on your experience, or select no experience / unable to assess.','☺'],
 ['D','ประสบการณ์ที่อยากให้ปรับปรุง','Areas for improvement','เมื่อเลือก “มี” ต้องตอบปัญหาและสิ่งที่ต้องการให้ปรับปรุงที่แสดงเพิ่ม','Selecting Yes reveals required questions about the issue and suggested improvement.','↗'],
 ['E','ความผูกพัน','Engagement','เลือกระดับที่ตรงกับความรู้สึกของท่าน โดยยึดข้อความกำกับคะแนน','Choose the level that reflects your feelings. Read the labels for each rating.','♡'],
 ['R','การแนะนำและบอกต่อ','Recommendation','พิจารณาจากประสบการณ์ของท่านกับวิทยาลัยฯ','Consider your experience with the School of Education.','↗'],
 ['C','การสื่อสาร','Communication','ประเมินการสื่อสาร และเลือกช่องทางที่ได้รับข่าวสาร','Rate communication and select the channels you receive information through.','◌'],
 ['K','ความเข้าใจเกี่ยวกับองค์กร','Organizational understanding','เลือก “ไม่ทราบ” ได้ ไม่จำเป็นต้องเดาคำตอบ','You may select Do not know. There is no need to guess.','◇'],
 ['O','ข้อเสนอแนะ','Suggestions','ส่วนนี้ข้ามได้ เล่าสิ่งที่อยากให้พัฒนาโดยไม่ระบุข้อมูลที่บอกตัวตน','This section is optional. Share improvements without identifying details.','✧']
 ];
 if(data.runtime?.public){definitions[0][3]='ข้อมูลจากหน้าที่ท่านเลือกกลุ่ม หลักสูตร และชั้นปี';definitions[0][4]='Context from your selected group, programme and study year.';}
 const sections=definitions.map(([code,th,en,helpTh,helpEn,icon])=>({code,th,en,helpTh,helpEn,icon,items:data.questions.filter(q=>key(q)===code).sort((a,b)=>a.id.localeCompare(b.id))}));
 const title=s=>t(s.th,s.en), inspect=()=>F01Validation.inspect(data.questions,answers);
 const nav=[];
 sections.forEach((s,i)=>{const b=make('button');b.type='button';b.append(make('span',String(i+1).padStart(2,'0'),'nav-num'),make('span','','nav-label'),make('span','','nav-count'));b.addEventListener('click',()=>show(i,true));$('section-nav').append(b);nav.push(b);});
 const rb=make('button');rb.type='button';rb.append(make('span','✓','nav-num'),make('span','','nav-label'));rb.addEventListener('click',()=>show(8,true));$('section-nav').append(rb);nav.push(rb);
 function progress(){
  const required=data.questions.filter(q=>visible(q)&&F01Validation.required(q)),done=required.filter(valid).length;
  $('progress-text').textContent=`${done} / ${required.length}`;$('progress').max=required.length||1;$('progress').value=done;
  $('first-missing').hidden=done===required.length;
  sections.forEach((s,i)=>{const qs=s.items.filter(q=>!q.fixed&&visible(q)),n=qs.filter(valid).length;nav[i].querySelector('.nav-label').textContent=title(s);nav[i].querySelector('.nav-count').textContent=n===qs.length?'✓':`${n}/${qs.length}`;nav[i].classList.toggle('complete',n===qs.length);nav[i].setAttribute('aria-label',`${title(s)} · ${n}/${qs.length}`);});
  nav[8].querySelector('.nav-label').textContent=t('ทบทวนคำตอบ','Review answers');
  Array.from($('questions').children).filter(c=>!c.hidden).forEach((c,i)=>c.querySelector('.question-num').textContent=String(i+1).padStart(2,'0'));
 }
 function change(q,value){
  if(Array.isArray(value)?value.length:value.trim())answers.set(q.id,value);else answers.delete(q.id);
  completed=false;$('finish-note').textContent='';
  data.questions.forEach(item=>{if(!visible(item))answers.delete(item.id);const c=$(`card-${item.id}`);if(!c)return;c.hidden=!visible(item);if(c.hidden){c.querySelectorAll('input').forEach(n=>n.checked=false);c.querySelectorAll('textarea').forEach(n=>n.value='');const counter=c.querySelector('.counter');if(counter)counter.textContent='0 / 500';}});progress();
 }
 function ratingIcon(q,value){
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 32 32');svg.setAttribute('class','rating-icon');svg.setAttribute('aria-hidden','true');
  const n=Number(value),sat=['S','C'].includes(key(q));
  const path=(name,attrs)=>{const node=document.createElementNS(svg.namespaceURI,name);Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v));svg.append(node);};
  if(sat){path('circle',{cx:16,cy:16,r:13,fill:'none',stroke:'currentColor','stroke-width':1.5});path('circle',{cx:11,cy:12,r:1.4,fill:'currentColor'});path('circle',{cx:21,cy:12,r:1.4,fill:'currentColor'});const mouths=['M10 23 Q16 15 22 23','M10 22 Q16 18 22 22','M10 21 L22 21','M10 19 Q16 25 22 19','M9 18 Q16 29 23 18'];path('path',{d:mouths[n-1],fill:'none',stroke:'currentColor','stroke-width':1.7,'stroke-linecap':'round'});}
  else {for(let i=0;i<5;i++)path('rect',{x:3+i*5.5,y:25-(i+1)*3.5,width:3.5,height:(i+1)*3.5,rx:1,fill:i<n?'currentColor':'#e4ddec'});}
  return svg;
 }
 function card(q,i){
  const c=make('fieldset',undefined,`card${q.rule.op==='eq'?' follow':''}`);c.id=`card-${q.id}`;c.hidden=!visible(q);
  const l=make('legend');l.append(make('span',String(i+1).padStart(2,'0'),'question-num'),make('span',text(q)));c.append(l,make('p',q.id+' · '+(q.fixed?(data.runtime?.public?t('ข้อมูลที่ท่านเลือก','Your selected context'):t('กำหนดจากคำเชิญ','Set by invitation')):F01Validation.required(q)?t('จำเป็นต้องตอบ','Required'):t('ไม่บังคับ','Optional')),'question-code'));
  if(q.fixed){c.append(make('div',fixed(q),'fixed'));return c;}
  if(q.type==='text'){
   const input=make('textarea');input.id=`answer-${q.id}`;input.maxLength=500;input.rows=3;input.required=F01Validation.required(q);input.setAttribute('aria-label',text(q));input.placeholder=F01Validation.required(q)?t('ระบุสิ่งที่ต้องการให้ปรับปรุง โดยไม่ใส่ข้อมูลระบุตัวตน','Describe the improvement without identifying details'):t('พิมพ์ข้อเสนอแนะ หรือข้ามข้อนี้ได้','Share a suggestion, or leave this blank');input.value=answers.get(q.id)||'';
   const count=make('span',`${input.value.length} / 500`,'counter');count.id=`counter-${q.id}`;input.setAttribute('aria-describedby',count.id);input.addEventListener('input',()=>{change(q,input.value);count.textContent=`${input.value.length} / 500`;});c.append(input,count);
  }else{
   if(q.type==='multi_choice')c.append(make('p',t('เลือกได้มากกว่า 1 ข้อ','Select all that apply'),'multi-hint'));
   const opts=make('div',undefined,`choices${q.type==='integer_scale'?' scale':''}`);
   q.options.forEach(o=>{const isRating=q.type==='integer_scale'&&/^[1-5]$/.test(o.value),wrap=make('label',undefined,`choice${isRating?' rating':''}`),input=make('input');input.type=q.type==='multi_choice'?'checkbox':'radio';input.name=q.id;input.value=o.value;const v=answers.get(q.id);input.checked=Array.isArray(v)?v.includes(o.value):v===o.value;wrap.append(input);if(isRating)wrap.append(ratingIcon(q,o.value),make('span',o.value,'score'));wrap.append(make('span',label(o)));opts.append(wrap);input.addEventListener('change',()=>change(q,q.type==='multi_choice'?Array.from(opts.querySelectorAll('input:checked')).map(n=>n.value):input.value));});c.append(opts);
  }
  const clear=make('button',t('ล้างคำตอบข้อนี้','Clear this answer'),'clear');clear.type='button';clear.addEventListener('click',()=>{c.querySelectorAll('input').forEach(n=>n.checked=false);c.querySelectorAll('textarea').forEach(n=>n.value='');const counter=c.querySelector('.counter');if(counter)counter.textContent='0 / 500';change(q,'');});c.append(clear);return c;
 }
 function review(){
  const {requiredMissing,optionalMissing}=inspect(),active=data.questions.filter(q=>!q.fixed&&visible(q)),done=active.filter(valid).length;
  $('review-summary').replaceChildren();
  [[t('ตอบแล้ว','Answered'),done,t('จากข้อที่แสดงทั้งหมด','Across visible items'),'answered'],[t('ข้อบังคับที่ยังขาด','Required remaining'),requiredMissing.length,t('ต้องครบก่อนยืนยัน','Complete before confirming'),'missing'],[t('ข้อเสนอแนะที่เว้น','Optional remaining'),optionalMissing.length,t('ข้ามได้','May be left blank'),'neutral']].forEach(([txt,n,hint,cls])=>{const s=make('div',undefined,`review-stat ${cls}`);s.append(make('span',txt),make('strong',String(n)),make('small',hint));$('review-summary').append(s);});
  const warning=$('review-warning');warning.replaceChildren();warning.classList.toggle('all-done',!requiredMissing.length);warning.append(make('strong',requiredMissing.length?t(`ยังขาดข้อบังคับ ${requiredMissing.length} ข้อ`,`${requiredMissing.length} required items still need an answer`):t('ตอบข้อบังคับครบแล้ว','All required items are complete')),make('p',t('ข้ามได้เฉพาะหมวดข้อเสนอแนะ ตรวจคำตอบให้ตรงกับความตั้งใจก่อนยืนยัน','Only suggestions are optional. Check that your answers reflect your experience.')));
  if(requiredMissing.length){const b=make('button',t('ไปข้อแรกที่ยังไม่ตอบ →','Go to the first missing item →'),'warning-link');b.type='button';b.addEventListener('click',()=>go(requiredMissing[0]));warning.append(b);}
  $('review-list').replaceChildren();let first=true;
  sections.forEach((s,i)=>{const qs=s.items.filter(q=>!q.fixed&&visible(q)),left=qs.filter(q=>!valid(q)),items=$('missing-only').checked?left:s.items.filter(visible);if(!items.length)return;const group=make('details',undefined,'review-group');group.open=first;first=false;const summary=make('summary'),heading=make('span',undefined,'review-heading');heading.append(make('span',String(i+1).padStart(2,'0'),'review-number'),make('strong',title(s)));summary.append(heading,make('span',left.length?(s.code==='O'?t('ข้ามได้','Optional'):t(`ยังขาด ${left.length}`,`${left.length} remaining`)):t('ครบแล้ว','Complete'),`review-badge ${left.length&&s.code!=='O'?'pending':'done'}`),make('span','⌄','review-chevron'));group.append(summary);const list=make('div',undefined,'review-items');
   items.forEach(q=>{const blank=!q.fixed&&!valid(q),row=make('div',undefined,`review-item${blank?' is-missing':''}`),question=make('div',undefined,'review-question');question.append(make('span',q.id,'review-code'),make('strong',text(q)));const v=answers.get(q.id),ol=x=>{const o=q.options.find(o=>o.value===x);return o?label(o):x;};const answer=q.fixed?fixed(q):valid(q)?(Array.isArray(v)?v.map(ol).join(' · '):ol(v)):F01Validation.required(q)?t('จำเป็นต้องตอบ','Required'):t('เว้นไว้ได้ · ไม่บังคับ','Optional · left blank');const response=make('div',undefined,'review-response');response.append(make('p',answer,`review-answer${blank?' empty-answer':''}`));if(!q.fixed){const edit=make('button',blank?t('ตอบข้อนี้ →','Answer →'):t('แก้ไข','Edit'),'edit-answer');edit.type='button';edit.setAttribute('aria-label',`${t('แก้ไข','Edit')} ${q.id}`);edit.addEventListener('click',()=>go(q));response.append(edit);}row.append(question,response);list.append(row);});group.append(list);$('review-list').append(group);
  });if(!$('review-list').children.length)$('review-list').append(make('p',t('ไม่มีข้อที่ยังไม่ได้ตอบ','No unanswered items.'),'empty-state'));
 }
 function go(q){show(sections.findIndex(s=>s.code===key(q)));const c=$(`card-${q.id}`);c.classList.add('attention');c.scrollIntoView({block:'center',behavior:'instant'});c.querySelector('input,textarea')?.focus({preventScroll:true});}
 function check(){const {requiredMissing:missing}=inspect();$('confirm-title').textContent=missing.length?t(`ยังขาดข้อบังคับ ${missing.length} ข้อ`,`${missing.length} required items remaining`):t('ตอบข้อบังคับครบแล้ว','All required items are complete');$('confirm-description').textContent=missing.length?t('กรุณาตอบข้อที่ขาดก่อนยืนยัน รวมถึงคำถามตามเงื่อนไขที่แสดง ข้ามได้เฉพาะข้อเสนอแนะ','Please complete all visible required items, including conditional questions. Only suggestions may be skipped.'):t('ทบทวนคำตอบแล้วจึงยืนยันจบการทดลอง ข้อเสนอแนะเว้นว่างได้','Review your answers before finishing the preview. Suggestions may be left blank.');$('confirm-breakdown').replaceChildren();sections.forEach(s=>{const n=missing.filter(q=>key(q)===s.code).length;if(n){const row=make('div');row.append(make('span',title(s)),make('strong',String(n)));$('confirm-breakdown').append(row);}});$('confirm-finish').disabled=!!missing.length;$('return-missing').hidden=!missing.length;$('confirm-finish').textContent=missing.length?t('ต้องตอบข้อบังคับให้ครบ','Complete required items first'):t('ยืนยันและดูหลักฐานตัวอย่าง','Confirm & see sample receipt');$('confirm-dialog').querySelector('.dialog-mark').textContent=missing.length?'!':'✓';if(connection&&!missing.length){$('confirm-description').textContent=t('เมื่อยืนยันจะบันทึกคำตอบในฐานพัฒนาและออกหลักฐานทดสอบ คำตอบที่ส่งแล้วแก้ไขไม่ได้','Confirm to save answers to the development database and issue a test receipt. Submitted answers cannot be edited.');$('confirm-finish').textContent=t('ยืนยันบันทึกคำตอบ','Confirm submission');}if(!$('confirm-dialog').open)$('confirm-dialog').showModal();}
 function show(index,focus=false){if(connection&&connection.client.state!=='editing'){if(connection.client.state==='issued')index=9;else return;}current=Math.max(0,Math.min(9,index));if(current===9&&!completed)current=8;const isReview=current===8,isReceipt=current===9;$('question-panel').hidden=current>=8;$('review-panel').hidden=!isReview;$('receipt-panel').hidden=!isReceipt;document.querySelector('.pager').hidden=isReceipt;nav.forEach((b,i)=>{if(i===current)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});if(isReview)review();else if(!isReceipt){const s=sections[current];$('step-label').textContent=t(`หมวดที่ ${current+1} / 8`,`SECTION ${current+1} / 8`);$('question-title').textContent=title(s);$('section-help').textContent=t(s.helpTh,s.helpEn);$('section-policy').textContent=s.code==='O'?t('ไม่บังคับ · ข้ามได้','OPTIONAL · may be skipped'):t('จำเป็นต้องตอบทุกข้อที่แสดง','REQUIRED · answer each visible item');$('section-icon').textContent=s.icon;$('questions').replaceChildren(...s.items.map(card));}$('prev').disabled=current===0;$('next').hidden=current>=8;$('next').textContent=current===7?t('ทบทวนคำตอบ →','Review answers →'):t('หมวดถัดไป →','Next section →');$('position').textContent=isReview?t('ทบทวนคำตอบ','Review'):`${current+1} / 8`;progress();if(focus){const target=$(isReceipt?'receipt-title':isReview?'review-title':'question-title');target.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:'instant'});}}
 function localize(){document.documentElement.lang=lang;document.querySelectorAll('[data-th][data-en]').forEach(n=>n.textContent=n.dataset[lang]);$('lang-th').setAttribute('aria-pressed',String(lang==='th'));$('lang-en').setAttribute('aria-pressed',String(lang==='en'));$('instructions-text').textContent=lang==='th'?data.instructions:data.instructions_en;navLabel();show(current);if($('confirm-dialog').open)check();connection?.localize();}
 function navLabel(){$('nav-toggle').textContent=$('section-nav').hidden?t('แสดงเมนู','Expand'):t('ย่อเมนู','Collapse');}
 ['th','en'].forEach(code=>$(`lang-${code}`).addEventListener('click',()=>{lang=code;$('download-status').textContent='';localize();}));
 document.querySelectorAll('.skip,.start-link').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();show(current>=8?0:current,true);}));
 $('nav-toggle').addEventListener('click',()=>{$('section-nav').hidden=!$('section-nav').hidden;$('nav-toggle').setAttribute('aria-expanded',String(!$('section-nav').hidden));navLabel();});
 $('first-missing').addEventListener('click',()=>{const q=inspect().requiredMissing[0];if(q)go(q);});
 $('prev').addEventListener('click',()=>show(current-1,true));$('next').addEventListener('click',()=>show(current+1,true));$('missing-only').addEventListener('change',review);$('finish').addEventListener('click',check);$('cancel-confirm').addEventListener('click',()=>$('confirm-dialog').close());$('return-missing').addEventListener('click',()=>{$('confirm-dialog').close();const q=inspect().requiredMissing[0];if(q)go(q);});$('confirm-finish').addEventListener('click',()=>{if(inspect().requiredMissing.length){check();return;}$('confirm-dialog').close();if(connection){connection.submit(answers);return;}completed=true;show(9,true);});$('back-review').addEventListener('click',()=>show(8,true));
 $('download-receipt').addEventListener('click',async()=>{
  if(connection){await connection.download();return;}
  if(!completed||inspect().requiredMissing.length)return;
  const btn=$('download-receipt');btn.disabled=true;
  try{
   const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=800;const ctx=canvas.getContext('2d');ctx.fillStyle='#faf7fd';ctx.fillRect(0,0,1200,800);ctx.fillStyle='#fff';ctx.fillRect(35,35,1130,730);ctx.fillStyle='#49337f';ctx.font='bold 42px sans-serif';ctx.fillText('NEXORA',70,110);ctx.font='26px sans-serif';ctx.fillText(t('หลักฐานการเข้าร่วมตัวอย่าง','Sample participation receipt'),70,165);ctx.fillStyle='#94602b';ctx.font='bold 28px sans-serif';ctx.fillText('DEMO · NOT VALID',70,230);ctx.fillStyle='#2c2539';ctx.font='25px sans-serif';ctx.fillText('F01 · Student experience',70,300);ctx.fillText('Academic year 2025 / 2568',70,344);ctx.font='20px monospace';ctx.fillText('NXR-DEMO-F01-2568-0001',70,410);ctx.font='20px sans-serif';ctx.fillText(t('รหัสตัวอย่างใช้ซ้ำเพื่อสาธิต ไม่ได้บันทึกในระบบ','Reusable demo reference. Not registered in a system.'),70,475);ctx.fillText(t('ไม่มีคำตอบหรือคะแนนในหลักฐานนี้','This receipt contains no answers or scores.'),70,520);ctx.fillText('School of Education University of Phayao',70,675);ctx.fillStyle='#615a70';ctx.font='18px sans-serif';ctx.fillText(t('ใช้รับชั่วโมงภาระงานหรือรางวัลจริงไม่ได้','Not valid for workload credits or prize claims.'),70,715);
   const svg=new XMLSerializer().serializeToString($('receipt-qr').querySelector('svg'));const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);await img.decode();ctx.imageSmoothingEnabled=false;ctx.drawImage(img,790,225,310,310);
   const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='NEXORA-DEMO-receipt.png';a.click();$('download-status').textContent=t('สร้างไฟล์หลักฐานตัวอย่างแล้ว ตรวจในรายการดาวน์โหลดของเบราว์เซอร์','Sample receipt prepared. Check your browser downloads.');
  }catch(error){$('download-status').textContent=t('ดาวน์โหลดไม่สำเร็จ กรุณาลองอีกครั้ง หรือบันทึกภาพหลักฐานจากหน้าจอ','Download failed. Try again or save a screenshot of the receipt.');}finally{btn.disabled=false;}
 });
 localize();
})();
