# Generated by Django 5.2.17 on 2026-09-15 20:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_review_revisions'),
        ('rounds', '0003_population_locking_and_retired_bindings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cutoff', models.DateTimeField()),
                ('engine_commit', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{40}\\Z', 'Use a full commit SHA.')])),
                ('engine_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('input_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('manifest', models.JSONField()),
                ('status', models.CharField(choices=[('building', 'building'), ('complete', 'complete')], default='building', max_length=12)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('input_count', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('collection_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_runs', to='rounds.collectionround')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('population_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.populationsnapshot')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('collection_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.collectionround')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='calculations.calculationrun')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CalculationInputSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series_key', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('definition', models.JSONField()),
                ('payload', models.JSONField()),
                ('source_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('question_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('formula_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.indicatorbinding')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.respondentgroup')),
                ('round_instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.roundinstrument')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inputs', to='calculations.calculationrun')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator_code', models.CharField(max_length=20)),
                ('series_key', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('payload', models.JSONField()),
                ('result_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='calculations.calculationrun')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='calculations.calculationinputsnapshot')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='calculationrun',
            index=models.Index(fields=['collection_round', 'created_at'], name='calc_run_round_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.UniqueConstraint(fields=('collection_round', 'input_hash'), name='calc_run_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('input_count', 0), ('result_count', 0), ('result_hash', ''), ('sealed_at__isnull', True), ('status', 'building')), models.Q(('input_count__gt', 0), ('result_count__gt', 0), ('sealed_at__isnull', False), ('status', 'complete'), models.Q(('result_hash', ''), _negated=True)), _connector='OR'), name='calc_run_seal_state'),
        ),
        migrations.AddConstraint(
            model_name='calculationrequest',
            constraint=models.UniqueConstraint(fields=('collection_round', 'actor', 'idempotency_key'), name='calc_request_actor_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='calculationinputsnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'series_key'), name='calc_input_run_series_unique'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.UniqueConstraint(fields=('run', 'series_key'), name='calc_result_run_series_unique'),
        ),
    ]
