# Generated by Django 5.2.17 on 2026-09-15 21:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_snapshot_guards'),
        ('rounds', '0003_population_locking_and_retired_bindings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('review_token', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_request', to='calculations.calculationrun')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StoredSourceSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_kind', models.CharField(default='f06_revisions', max_length=32)),
                ('round_instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stored_calculations', to='rounds.roundinstrument')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stored_source', to='calculations.calculationrun')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ResultDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('approved', 'approved'), ('returned', 'returned')], max_length=12)),
                ('reason', models.TextField()),
                ('reviewed_token', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='calculations.resultdecision')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='calculations.resultreviewrequest')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['approved', 'returned'])), name='result_decision_outcome')],
            },
        ),
    ]
