# Generated by Django 5.2.17 on 2026-09-16 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0007_demo_datasets'),
        ('rounds', '0003_population_locking_and_retired_bindings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_code', models.CharField(max_length=100)),
                ('session_code', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.populationmember')),
                ('round_instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='rounds.roundinstrument')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ActivityRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('revision_requested', 'revision_requested'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=24)),
                ('payload', models.JSONField()),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='calculations.activityrecord')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='activityrecord',
            constraint=models.UniqueConstraint(fields=('round_instrument', 'member', 'activity_code', 'session_code'), name='f05_activity_session_person'),
        ),
        migrations.AddConstraint(
            model_name='activityrevision',
            constraint=models.UniqueConstraint(fields=('record', 'number'), name='f05_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='activityrevision',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'revision_requested', 'accepted', 'rejected'])), name='f05_revision_status'),
        ),
    ]
