# Generated by Django 5.2.17 on 2026-09-17 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_self_assessment_result_permissions'),
        ('rounds', '0003_population_locking_and_retired_bindings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.reportingperiod')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_th', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('responsibility_th', models.TextField(max_length=2000)),
                ('responsibility_en', models.TextField(max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Exclusive end of the assessed appointment segment')),
                ('appointment_kind', models.CharField(choices=[('substantive', 'ดำรงตำแหน่ง / Substantive'), ('acting', 'รักษาการ / Acting')], default='substantive', max_length=12)),
                ('source_reference', models.CharField(max_length=1000)),
                ('eligibility_basis', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'ร่าง / Draft'), ('ready', 'ตรึงแล้ว / Ready'), ('superseded', 'แทนที่แล้ว / Superseded'), ('exempt', 'ยกเว้น / Exempt')], default='draft', max_length=12)),
                ('status_reason', models.TextField(blank=True, max_length=2000)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='leadership.annualplan')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='leadership.annualtarget')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name_th', models.CharField(max_length=240)),
                ('name_en', models.CharField(max_length=240)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(choices=[('ST1', 'ST1 สายวิชาการ / Academic'), ('ST2', 'ST2 สายสนับสนุน / Support')], max_length=3)),
                ('relationship', models.CharField(max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility', to='leadership.annualtarget')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leadership.person')),
            ],
        ),
        migrations.AddField(
            model_name='annualtarget',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leadership.person'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('DE', 'คณบดี / Dean'), ('VD', 'รองคณบดี / Vice dean'), ('AS', 'ผู้ช่วยคณบดี / Assistant dean'), ('PC', 'ประธานหลักสูตร / Programme chair')], max_length=2)),
                ('title_th', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.AddField(
            model_name='annualtarget',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='leadership.position'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name_th', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leadership.programme'),
        ),
        migrations.AddConstraint(
            model_name='annualplan',
            constraint=models.UniqueConstraint(fields=('scope', 'fiscal_year'), name='f04_plan_scope_year'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='f04_person_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='eligibility',
            constraint=models.UniqueConstraint(fields=('target', 'person'), name='f04_eligible_target_person'),
        ),
        migrations.AddConstraint(
            model_name='eligibility',
            constraint=models.CheckConstraint(condition=models.Q(('group_code__in', ['ST1', 'ST2'])), name='f04_eligible_group'),
        ),
        migrations.AddConstraint(
            model_name='annualtarget',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='f04_target_dates'),
        ),
        migrations.AddConstraint(
            model_name='annualtarget',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'ready', 'superseded', 'exempt'])), name='f04_target_status'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='f04_programme_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='f04_position_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('programme__isnull', False), ('role', 'PC')), models.Q(('programme__isnull', True), ('role__in', ['DE', 'VD', 'AS'])), _connector='OR'), name='f04_position_role_programme'),
        ),
    ]
