from .common import manual, section, limitations


def build():
    sections=[
        section('orientation','อ่านโครงการให้เข้าใจก่อนแก้',[
            'NEXORA เป็น Django application ที่แสดงหน้าเว็บฝั่งเซิร์ฟเวอร์ ใช้ PostgreSQL และ Django migrations เป็นแหล่งเดียวของ schema ไม่ใช่ SPA และไม่มีบริการ FineReport ภายนอกเป็นส่วนประกอบบังคับ',
            'คู่มือนี้อ้างอิงโค้ดฐาน Interactive Pages 25f1271 และคู่มือภาพประกอบรุ่น 1.1 ประวัติใน docs บางเล่มเป็นรายงาน increment เก่า ให้ใช้โค้ดปัจจุบันและ docs/system-readiness-th.md แยกความสามารถจริงออกจากงานที่ยังไม่ทำ',
            'ไม่มี credentials หรือข้อมูลผู้ตอบจริงในคู่มือ ตัวอย่างคำสั่งใช้สำหรับสภาพแวดล้อมที่ผู้พัฒนาตั้งค่าเอง ต้องตรวจปลายทางฐานข้อมูลก่อนสั่งงานที่เขียนข้อมูล'],
            checks=['เริ่มจาก edpex/urls.py เพื่อดู route','อ่าน service และ permission ก่อน view/template','อ่าน tests ของโมดูลที่จะแก้','ตรวจ migrations และ SQL guards หากแก้ข้อมูลที่มีประวัติ','ใช้ฐานทดสอบแยกจากฐานใช้งาน']),
        section('architecture','โครงสร้างเว็บและเส้นทางคำขอ',flow=[
            ('Browser','HTML/CSS/JS, session และ CSRF'),
            ('Django routing + middleware','edpex/urls.py, headers, login, language'),
            ('Views / Forms / API','ตรวจ method, shape, owner และ scope'),
            ('Domain services','transaction, permission, version, workflow'),
            ('PostgreSQL + guards','models, constraints, triggers, audit'),
            ('Template / aggregate response','ส่งเฉพาะข้อมูลที่อนุญาตให้เห็น')],
            note='เส้นทางคำนวณต้องผ่านบริการและ snapshot ส่วนเส้นทางคู่มืออ่านไฟล์เอกสารคงที่ ไม่มีการเขียนคำตอบหรือสถานะรับรอง'),
        section('folders','แผนที่โฟลเดอร์และความรับผิดชอบ',columns=['ตำแหน่ง','หน้าที่'],rows=[
            ('edpex/','settings.py กำหนด profile/middleware; urls.py รวม route; wsgi.py เป็นจุดเริ่ม deployment'),
            ('apps/accounts/','องค์กร scope สมาชิก role grant บัญชี พื้นที่ทำงาน หลังบ้าน headers/health และ shared templates/static'),
            ('apps/catalog/','รุ่นแบบ คำถาม ตัวเลือก คำแปล ตัวชี้วัด binding และหน้า preview'),
            ('apps/rounds/','ปฏิทิน ช่วงรายงาน รอบ บริบท ประชากร frozen และแหล่งข้อมูล'),
            ('apps/surveys/','F01–F04 รหัสคำเชิญ session ชั่วคราว คำตอบแยกตัวตน schema และ source adapter'),
            ('apps/selfassessments/','F06 owner assignment, revision, UI และ session API'),
            ('apps/calculations/','สูตร typed inputs, snapshot, replay, F05, review, approved dashboard, demo, visualization, quality'),
            ('apps/auditlog/','AuditEvent และบริการอ่าน/เขียนเหตุการณ์ตาม scope'),
            ('apps/manuals/','ศูนย์คู่มือ หน้าอ่าน และดาวน์โหลด PDF ที่สร้างไว้ล่วงหน้า'),
            ('catalog/','นิยาม JSON มาตรฐานและ indicator_reference.json; ไม่ใช้แทนทะเบียนจริง'),
            ('docs/manuals/','เนื้อหาที่ build แล้ว PDF font ที่มี license และ manifest ของคู่มือ'),
            ('scripts/ / tests/','เครื่องมือเฉพาะงาน/สร้างคู่มือ และ regression tests'),
            ('.github/workflows/','CI และ workflow ทดสอบ/จัดการ Supabase ที่ต้องเรียกตามเงื่อนไข')]),
        section('models','ความสัมพันธ์ข้อมูลหลัก',columns=['สายข้อมูล','ความสัมพันธ์และข้อจำกัด'],rows=[
            ('สิทธิ์','Organization มี AccessScope; User เชื่อมองค์กรผ่าน Membership; RoleAssignment ผูก Membership + Role + Scope + ช่วงเวลา; scope ลูกต้องอนุญาต descendants ชัดเจน'),
            ('แบบฟอร์ม','Instrument มี InstrumentVersion; รุ่นมี Question/QuestionOption/InstrumentContent/IndicatorBinding; TranslationBundle เก็บ ContentTranslation ที่ตรวจตามต้นฉบับ'),
            ('รอบ','Calendar มี ReportingPeriod; CollectionRound ผูก scope/period/population; RoundInstrument ตรึงรุ่นแบบ คำแปล และ context'),
            ('ประชากร','PopulationSnapshot มี PopulationMember; เมื่อ frozen ห้ามแก้เป็นทะเบียนเคลื่อนไหว'),
            ('สำรวจ','SurveyProfile ผูก RoundInstrument; Invitation ใช้ตรวจสิทธิ์; AnonymousSession เก็บร่างชั่วคราว; AnonymousResponse แยกจากทะเบียนคำเชิญ'),
            ('F06','SelfAssessmentAssignment ผูกเจ้าของและสมาชิกประชากร; SelfAssessmentRevision เก็บสถานะและคำตอบแต่ละ revision'),
            ('F05','ActivityRecord ผูกคน/กิจกรรม/ครั้ง; ActivityRevision เก็บ payload และผลตรวจแบบ append-only'),
            ('ผล','CalculationRun มี CalculationInputSnapshot และ IndicatorResult; StoredSourceSelection ตรึงที่มา; ResultReviewRequest และ ResultDecision เก็บการส่งตรวจ/ตัดสิน'),
            ('สาธิต','DemoDataset / DemoSeries แยกจากคำตอบจริงและชุดผลรับรอง ใช้ replay ตรวจค่าก่อนแสดง')]),
        section('workflow-round','Workflow: เตรียมแบบและรอบ',flow=[
            ('Draft instrument','แก้เฉพาะรุ่นร่าง'),('Translation review','ตรวจข้อความตรง source revision'),
            ('Published version','ตรึงเนื้อหาและคำแปล'),('Draft round + population','กำหนดช่วง บริบท ทะเบียน'),
            ('Ready','ตรึงประชากรและตรวจความพร้อม'),('Open then closed','ตรวจเวลารับและปิดพร้อมเหตุผล')],
            paragraphs=['CollectionRound มี enum สำหรับหลายสถานะ แต่ห้ามสรุปจากชื่อ enum ว่า workflow ทุกขั้นเขียนสถานะรอบสำเร็จแล้ว ผลคำนวณ/การรับรองเก็บใน CalculationRun/ResultDecision แยกจากสถานะรอบ อ่าน services ที่ใช้จริงก่อนเพิ่ม transition',
                        'การรับคำตอบใช้เงื่อนไขสถานะ open และ open_at <= เวลา < close_at การมี deadline ไม่ได้ทำให้ข้อมูลหลัง deadline ผ่านเงื่อนไขอื่นโดยอัตโนมัติ']),
        section('workflow-survey','Workflow: F01–F04 แยกคำเชิญจากคำตอบ',flow=[
            ('Issue invitation','ออกรหัสให้หน่วยในทะเบียน'),('Exchange code','POST รหัส → cookie session'),
            ('Draft','บันทึกร่างและตรวจเงื่อนไข'),('Submit once','ยืนยันและใช้สิทธิ์ใน transaction'),
            ('AnonymousResponse','บันทึกคำตอบแยกจากคำเชิญ'),('Receipt','จบ session; ไม่เปิด raw answer ย้อนกลับ')],
            paragraphs=['apps/surveys/web.py ตรวจ HTTPS ยกเว้น loopback/test ที่เจาะจง ตั้ง no-store และ CSP การส่ง code ไม่วางใน URL และไม่ใช้บัญชี staff เป็นตัวแทนระบุตัวผู้ตอบ',
                        'schema.py เป็นสัญญาการแสดง/normalize คำถามตามเงื่อนไข ไม่รับ fields ที่อยู่นอกสัญญาไปคำนวณ ต้องรักษาการล้าง child answers เมื่อเงื่อนไขไม่เข้า',
                        'การเปลี่ยนรหัสคำเชิญยกเลิกรหัส/ร่างเดิมก่อนส่ง; เมื่อส่งแล้วไม่เปิดให้แก้คำตอบ F01–F04 ห้ามเพิ่ม foreign key หรือ audit metadata ที่เชื่อมผู้ตอบกับคำตอบโดยไม่ได้ทบทวน privacy model']),
        section('workflow-staff','Workflow: F06 และ F05',columns=['F06 self-report','F05 verified activity'],rows=[
            ('Assignment ตรึงเจ้าของ หน้าที่ ระดับคาดหวัง','ActivityRecord ตรึงบุคลากร กิจกรรม และครั้ง'),
            ('Owner บันทึก draft/submitted เป็น revision ใหม่','ผู้บันทึกทำ draft/submitted พร้อมเหตุผลและ evidence reference'),
            ('แก้และส่งใหม่ได้เมื่อรอบยังรับคำตอบ; ไม่บังคับ evidence','ผู้ตรวจทำ accepted/revision_requested/rejected พร้อมหลักฐานและเหตุผล'),
            ('เลือก submitted revision ตาม cutoff ไม่ใช้ draft ล่าสุดแทนโดยพลการ','stored_series เลือก revision ตาม cutoff และกติกาการตรวจรับ'),
            ('self.read/self.write ต้อง owner ตรง ไม่ใช่ reviewer form','source.manage เปิดรายการ; calculation.validate เพิ่มสิทธิ์ตรวจ')],
            paragraphs=['F05 ต้องตรวจชั่วโมงกับช่วงเวลา ห้ามตรวจรับก่อนกิจกรรมจบ และตรวจกรณีชั่วโมงสูง/เวลาซ้อน เก็บประวัติด้วย models และ PostgreSQL guards ไม่อาศัย disabled field บนหน้าเว็บอย่างเดียว']),
        section('workflow-result','Workflow: คำนวณ ตรวจ และนำเสนอ',flow=[
            ('Select stored sources','เลือกตาม round instrument และ cutoff'),
            ('Prepare + validate','typed specification, population, source hash'),
            ('Calculate + seal','engine คำนวณและตรึง snapshot/ผล'),
            ('Request review','ผูก review token กับ hash ชุดผล'),
            ('Replay + coverage','ตรวจผลซ้ำและ expected series'),
            ('Decision + disclosure','รับรอง/ส่งกลับ แล้วผ่านการซ่อนค่าก่อน UI')],
            paragraphs=['engine.py / types.py / codec.py / revisions.py เป็นส่วนของ engine identity การเปลี่ยนไฟล์เหล่านี้กระทบการตรวจผลย้อนหลัง ต้องตรวจ version/compatibility และ regression ของ sealed runs',
                        'review_summary() เป็นทางอ่าน aggregate ที่ตรวจ replay และ coverage พร้อมซ่อนกลุ่มเล็ก/หลาย generation อย่าให้ dashboard อ่าน result.payload ดิบข้ามบริการนี้',
                        'การรับรองทั่วไปแยกคนคำนวณ/ส่งตรวจกับผู้รับรอง มี exception ที่ edpex_admin_self_review ตรวจเฉพาะบัญชี/scope/role ตาม migration เดิม ไม่ใช่ superuser bypass ทั่วไป',
                        'Correction เก็บ run/decision ใหม่และอ้างผลก่อนหน้า ไม่ update ผลเก่า Dashboard เลือกผลรับรองที่ยังไม่ถูกแทนที่ และไม่ถือว่ารับรองแล้วคือเผยแพร่สาธารณะ']),
        section('permission-map','ขอบเขตสิทธิ์ที่ต้องรักษา',columns=['งาน','สิทธิ์หลัก'],rows=[
            ('จัดแบบ/ภาษา','catalog.read, catalog.edit, translation.review, catalog.publish ตาม action'),
            ('รอบ/ประชากร','calendar.manage, round.manage, population.manage, source.manage ตาม action'),
            ('มอบหมาย F06','selfassessment.assign + population.manage'),
            ('เจ้าของตอบ F06','self.read / self.write พร้อม owner ที่ตรง'),
            ('คำนวณ','calculation.run; source adapters ตรวจต้นทางตาม workflow'),
            ('ส่งตรวจ','result.submit + calculation.validate'),
            ('อ่านผลรวม/Dashboard','result.review + calculation.validate'),
            ('รับรอง','result.approve เพิ่มจากสิทธิ์ตรวจ และกติกาแยกคน'),
            ('บัญชี/ประวัติ','role.manage / audit.read ตามงาน')],
            paragraphs=['permissions.py ตรวจ persisted user/membership/grant ทุกครั้ง ช่วงสิทธิ์เป็น [active_from, active_until) การสืบสิทธิ์ลง scope ลูกเป็น opt-in และการมอบสิทธิ์ต้องไม่ขยายเกินของผู้มอบ',
                        'Preset ที่มีอยู่: organization-manager-v1, catalog-reader-v1, self-service-v1, calculation-operator-v1, result-submitter-v1 และ system-administrator-v1 ชื่อหน้าที่ในคู่มือไม่ใช่การสร้าง Role ใหม่อัตโนมัติ']),
        section('routes','แผนที่ URL และ API',columns=['URL / route family','หน้าที่'],rows=[
            ('/login/ /workspace/ /account/password/','เข้าสู่ระบบ พื้นที่ทำงาน และเปลี่ยนรหัสผ่าน'),
            ('/survey/ /survey/answer/','ทางเข้ารหัสและหน้าแบบสำรวจแยกตัวตน'),
            ('/workspace/self-assessments/','งาน F06 ของเจ้าของบัญชี'),
            ('/workspace/<scope>/catalog/ และ assessments/preview/','คลังและดูแบบประเมิน'),
            ('/workspace/<scope>/rounds/ surveys/ collection/ activities/','เตรียมรอบ/เก็บ F01–F04/F06/F05'),
            ('/workspace/<scope>/results/<run>/','ส่งตรวจและตัดสินชุดผลรวม'),
            ('/workspace/<scope>/insights/ visualization/ quality/','ผลรับรอง เปรียบเทียบ Dashboard และคุณภาพข้อมูล'),
            ('/workspace/<scope>/administration/','หลังบ้าน ตั้งค่า และ audit'),
            ('/manuals/ /manuals/<slug>/ /manuals/<slug>/download/','ศูนย์คู่มือ หน้าอ่าน และ PDF จาก allowlist'),
            ('/health/live/ /health/ready/','สถานะบริการและฐานข้อมูลแบบไม่มีรายละเอียดภายใน'),
            ('/api/v1/me/self-assessments/','GET งานตน; detail GET; draft/submit POST'),
            ('/api/v1/round-instruments/<id>/calculate/','POST คำนวณ F06'),
            ('/api/v1/calculation-runs/<id>/...','review-request POST; review GET; decision POST')],
            note='UUID และ slug ในตารางเป็น placeholder ไม่ใช่รหัสใช้งานจริง API F06 ใช้ session same-origin และ CSRF ไม่ใช่ bearer token ดู request/response แบบเต็มใน docs/f06-api.openapi.json'),
        section('api-contract','สัญญา API และการจัดการข้อผิดพลาด',[
            'apps/selfassessments/api.py รับ JSON object ที่มี keys ตรงสัญญา จำกัด body 65,536 bytes ปฏิเสธ duplicate keys และค่าที่ไม่ finite ต้องรักษา validation ก่อน service',
            'expected_revision ป้องกันแท็บเก่าเขียนทับ idempotency_key ทำให้ส่งซ้ำ payload เดิมได้โดยไม่สร้างรายการซ้ำ หาก key เดิมกับ payload ต่างต้อง 409',
            'API คืน 401 เมื่อไม่เข้าสู่ระบบ, 403 เมื่อไม่มีสิทธิ์, 404 เมื่อไม่พบวัตถุ, 409 conflict และ 422 invalid request; CSRF rejection อาจเป็น HTML ของ Django อย่าสมมุติว่าทุก error เป็น JSON',
            'GET ใช้อ่านเท่านั้น การสร้าง/แก้/ส่ง/รับรองใช้ POST พร้อม CSRF ทดสอบว่า GET/HEAD download คู่มือไม่เปลี่ยนข้อมูลธุรกิจ']),
        section('local-setup','เตรียมสภาพแวดล้อมพัฒนา',steps=[
            ('สร้าง checkout แยก','ใช้ repository ที่ได้รับสิทธิ์ ตรวจ branch/commit และงานที่ยังไม่ commit ก่อนเริ่ม','ไม่เขียนทับการแก้ของผู้อื่น'),
            ('สร้าง virtual environment','ใช้ Python ที่รองรับ Django 5.2 ติดตั้ง requirements.txt ใน venv ของโครงการ','Django และ psycopg พร้อม'),
            ('กำหนดฐานแยก','กำหนด POSTGRES_HOST/PORT/DB/USER/PASSWORD สำหรับฐานชั่วคราวที่ตั้งใจใช้ หรือ profile Supabase development ที่ได้รับอนุญาต ตรวจชื่อฐานก่อนทำ migrations','ไม่ใช้ฐานจริงเป็นฐานทดสอบโดยไม่ตั้งใจ'),
            ('ตรวจ schema plan','ใช้ migrate --plan บนฐานพัฒนาใหม่ หรือ upgrade_survey_schema ตามการอัปเดตที่มีอยู่ อ่านแผนก่อน apply','ทราบตาราง/guards ที่จะเปลี่ยน'),
            ('เริ่ม local server','หลังตั้งค่าและ schema พร้อม ใช้ runserver 127.0.0.1:8000 สำหรับทดสอบบนเครื่องเดียว','เปิดเว็บทดสอบได้โดยไม่เผยแพร่สู่ภายนอก')],code='python -m venv .venv\npython -m pip install -r requirements.txt\npython manage.py check\npython manage.py migrate --plan\npython manage.py runserver 127.0.0.1:8000',
            note='รันคำสั่งด้วย Python ของ venv ที่เลือกไว้ คำสั่งนี้ไม่รวม credentials และไม่ apply schema ให้โดยอัตโนมัติ พิจารณาแผนและปลายทางก่อนใช้ migrate หรือ --apply'),
        section('schema-changes','แก้ schema และข้อมูลอ้างอิงอย่างมีวินัย',[
            'ใช้ Django migrations ระบบเดียว PostgreSQL constraints และ trigger guards อยู่ใน migrations ด้วย อย่าเพิ่ม SQL migration ระบบที่สองหรือแก้ตารางใน Supabase แล้วปล่อยให้ state ไม่ตรง',
            'ชื่อ Role และนิยาม permission ที่ใช้งานแล้วไม่ควรถูกขยายเงียบ ๆ คำสั่ง provision มี preview และต้อง --apply อย่างชัดเจน ตรวจผู้ใช้ scope และเหตุผลก่อนดำเนินการ',
            'เมื่อเปลี่ยนแบบหรือสูตร ต้องตรวจ compatibility, question ids, option score, group, dimension, unit และ stored source adapter พร้อม golden tests การแก้ถ้อยคำกับแก้การคำนวณเป็นคนละชนิดการเปลี่ยน',
            'indicator_reference.json เทียบรหัสกับเอกสารที่แนบ มี checksum และหน้าอ้างอิง กรณี 7.4-8/C3.2 ยังต้องเจ้าของนิยามยืนยัน ไม่เปลี่ยน catalog จากคำอธิบายกำกวมเอง']),
        section('front-end','ปรับหน้าเว็บโดยคงพฤติกรรมเดิม',[
            'portal/base.html และ surveys/base.html โหลด shared design-system.css และ usability.js หน้า admin ใช้ templates/admin/base_site.html และ admin-theme.css รักษาโครง main/sidebar/header และอย่าวางเมนูนอก navigation',
            'แบบประเมินใช้ section navigation, radio cards และ draft/submit ที่แยกกัน workspace.js จัดหมวด; usability.js ดูแล unsaved warning/error summary/keyboard โดยไม่เก็บคำตอบใน localStorage',
            'อย่าเปลี่ยน name/value ของ inputs เพื่อความสวยงาม เพราะสัมพันธ์กับ form/parser และสูตร ต้องคง labels, focus, disabled/readonly, CSRF และ hidden revision fields',
            'กราฟใช้ SVG/CSS/JavaScript ภายใน ไม่มี CDN ผลจริงต้องผ่าน disclosure; ค่า 0 แสดง 0.00 ส่วน suppressed ใช้ขีดและข้อความ ห้ามฝังค่าใน data attributes ของรายการที่ซ่อน'],
            checks=['ตรวจหน้ากว้าง/มือถือ/zoom','ทดสอบ keyboard และไม่มี JS','ตรวจไทย-อังกฤษ','ทดสอบ invalid form และ stale revision','ไม่ทำให้ sticky element บัง controls']),
        section('manual-system','พัฒนาและอัปเดตศูนย์คู่มือ',[
            'ต้นฉบับเนื้อหาอยู่ที่ scripts/manuals/common.py, respondents.py, operations.py และ developer.py ใช้ข้อมูลกลุ่ม/แบบจาก catalog สร้าง docs/manuals/content/manuals.json หนึ่งแหล่งสำหรับหน้าเว็บและ PDF',
            'scripts/build_manuals.py สร้าง PDF ล่วงหน้าด้วย WeasyPrint/Pango เพื่อจัดวางภาษาไทย พร้อมสารบัญและหมายเลขหน้า จึงไม่ต้องติดตั้งเครื่องมือ PDF บน Windows เพื่อดาวน์โหลดคู่มือ',
            'PDF อยู่ใต้ docs/manuals/pdf ไม่อยู่ใน static URL สาธารณะ แอปตรวจ slug จากรายการและสิทธิ์เอกสารก่อน FileResponse คู่มือผู้ตอบ 17 กลุ่มอ่านได้โดยไม่ login; คู่มือผู้ปฏิบัติงาน/นักพัฒนาให้บัญชีที่เข้าสู่ระบบอ่านได้ ไม่มีข้อมูลจริงหรือ secret ในเอกสาร',
            'เมนูใน portal และลิงก์ในหน้า survey นำไปศูนย์เดียวกัน คำค้นหาคู่มือค้นเฉพาะเอกสาร ไม่ค้นคำตอบผู้ใช้ การเปิดคู่มือในอีกแท็บไม่บันทึกงานที่ยังกรอกค้าง',
            'ภาพอยู่ใน apps/manuals/static/manuals/illustrations เป็นภาพจำลองข้อมูลสมมุติ ไม่มีข้อมูลส่วนตัว นิยามและแหล่งอ้างอิงอยู่ใน scripts/manuals/illustrations.py; script build_manual_illustrations.py สร้าง PNG ด้วย WeasyPrint/PyMuPDF โดยไม่ใช้ฐานข้อมูลจริง ภาพมีข้อความทดแทน คำอธิบายหมายเลข และ checksum ในต้นฉบับคู่มือ',
            'หลังแก้เนื้อหา ให้ build ใหม่พร้อม manifest แล้วตรวจทุก PDF ด้วยการ render อย่าแก้ PDF โดยไม่อัปเดตต้นฉบับ HTML/JSON'],code='python -m pip install -r docs/manuals/requirements-build.txt\npython scripts/build_manual_illustrations.py\npython scripts/build_manuals.py\npython manage.py test tests.test_manuals',
            note='ฟอนต์ Sarabun แบบ Regular/Bold และ OFL license อยู่ใน docs/manuals/fonts ใช้เพื่อให้อ่านภาษาไทยได้สม่ำเสมอ ไม่ดาวน์โหลด font จากเครือข่ายขณะผู้ใช้เปิด PDF'),
        section('testing','ทดสอบให้ตรงความเสี่ยงของงาน',columns=['งานที่แก้','หลักฐานที่ต้องตรวจ'],rows=[
            ('สูตร/นิยาม','golden result, invalid input, rounding, replay และ compatibility ของผลเก่า'),
            ('สิทธิ์','own vs other owner, same vs other scope, inactive/revoked/expired grant และไม่ใช้ staff bypass'),
            ('ข้อมูลส่วนตัว','suppression ใน HTML/CSV/attributes; ไม่เชื่อมคำเชิญกับคำตอบ'),
            ('workflow','draft → submit → review → decision, idempotency, stale revision, correction'),
            ('คู่มือ','ครบ 17 group mappings, 26 PDFs, auth guard, allowlist/path traversal, file checksum และ GET ไม่เขียนข้อมูล'),
            ('UI','semantic form values, keyboard, invalid state, mobile/desktop และ browser visual inspection'),
            ('deployment','settings profile, migration plan, dependency health, restore rehearsal และ rollback rehearsal')],code='python manage.py check\npython manage.py test tests.test_manuals tests.test_quality_upgrade\npython manage.py test tests.test_assessment_preview tests.test_visualization',
            note='ใช้ PostgreSQL ทดสอบที่แยกและมีสิทธิ์สร้างฐานทดสอบตาม Django runner เครื่องมือ QA ชั่วคราวในสภาพแวดล้อมพัฒนาไม่ใช่ dependency ของแอปที่ส่งให้ผู้ใช้'),
        section('deployment','ติดตั้ง อัปเดต และย้อนรุ่น',steps=[
            ('ตรวจ release','ตรวจ commit, base commit และ SHA-256 ของ git bundle ตาม release.json','รู้ว่าแพ็กเกจเป็นโค้ดรุ่นใด'),
            ('เตรียมแบบไม่แตะฐาน','ใช้ nexora_web_update.py --install-only เพื่อสร้าง checkout แยกและตรวจ bundle','ได้โฟลเดอร์ NEXORA-WEB-<commit> โดยไม่เปิดเว็บ'),
            ('ตรวจแผน schema','อ่าน SCHEMA-UPDATE.md และผล upgrade_survey_schema ใช้ --apply-schema เฉพาะตามแผนที่อนุญาต','ไม่มี unrelated migration ถูก apply โดยเงียบ'),
            ('เปิดและตรวจรับ','ตัวเปิด local ใช้ development server บน loopback ตรวจเมนู ฟอร์ม ผลจริง และ PDF','ระบบรุ่นใหม่ทำงานตรงคู่มือ'),
            ('ย้อนโค้ดเมื่อจำเป็น','หยุด process ใหม่แล้วเปิด checkout/ตัวเปิดรุ่นก่อนที่ยังคงไว้ ถ้ามี schema เปลี่ยนต้องประเมิน compatibility และแผนคืนฐานแยก','ไม่สั่ง reverse migration หรือลบข้อมูลโดยคาดเดา')]),
        section('production','Production และการดูแลข้อมูลสำคัญ',[
            'กำหนด NEXORA_ENVIRONMENT=production, DJANGO_DEBUG=false, DJANGO_ALLOWED_HOSTS ที่ชัดเจน และ DJANGO_SECRET_KEY ที่เป็นความลับอย่างน้อย 50 ตัวอักษร โค้ดปฏิเสธการตั้งค่าที่ไม่ผ่าน guard',
            'ใช้ WSGI server/reverse proxy/HTTPS และ collectstatic ตามสภาพแวดล้อม ไม่เปิด Django runserver เป็นระบบจริง NEXORA_TRUST_HTTPS_PROXY=true ใช้ได้เฉพาะ proxy ที่ล้าง forwarding header จาก client และตั้งเองอย่างเชื่อถือได้',
            'อย่าเปลี่ยน SECRET_KEY ทุกครั้งที่ restart เพราะสัมพันธ์กับ session/signing/HMAC รหัสเข้าถึง การเปลี่ยน key ต้องวางแผนออก session/รหัสใหม่',
            'login throttling ใช้ AccessThrottle ในฐาน นับบัญชี 12 และ peer address 300 ครั้ง/10 นาที ไม่เชื่อ X-Forwarded-For จาก client ทดสอบเครือข่ายร่วม/proxy ก่อนเปิดให้ผู้ใช้จำนวนมาก',
            '/health/live/ ตรวจ process ตอบได้; /health/ready/ ตรวจต่อฐานและตารางหลักบางส่วน ตอบ generic 503 เมื่อผิดปกติ ไม่ใช่ full integrity scan หรือ SLA'],
            code='python manage.py collectstatic --noinput\npython manage.py check --deploy\npython scripts/backup_database.py --output /protected-backups/nexora-new.dump',
            note='คำสั่งสำรองต้องมี pg_dump และ environment ฐานที่ระบุชัด ใช้ชื่อไฟล์ใหม่ โฟลเดอร์จำกัดสิทธิ์ และเก็บ credentials นอก repository'),
        section('backup','สำรอง กู้คืน และรับมือเหตุขัดข้อง',steps=[
            ('สร้าง backup','รัน backup_database.py ใน environment ฐานที่ตั้งใจใช้ ตรวจ .dump และ .dump.json พร้อม SHA-256','มี archive ที่ไม่ทับไฟล์เก่าและหลักฐานขนาด/เวลา'),
            ('ตรวจ restore แยก','นำ archive ไปกู้คืนในฐานแยกที่เตรียมสำหรับทดสอบด้วยเครื่องมือ PostgreSQL ตรวจ schema/จำนวนรายการสำคัญและ workflow อ่านข้อมูล','มีหลักฐานกู้คืนได้จริง ไม่อาศัยแค่ checksum'),
            ('บันทึก RPO/RTO','ตกลงความสูญเสียข้อมูลและเวลาหยุดที่ยอมรับได้กับเจ้าของระบบ บันทึกเวลาทดสอบและ retention','กำหนดความพร้อมบริการจากหลักฐาน'),
            ('เมื่อบริการขัดข้อง','ตรวจ health/log ที่ไม่เปิด secrets, connection, schema และการตั้ง proxy ก่อน retry งานเขียน ตรวจ receipt/idempotency เพื่อไม่สร้างรายการซ้ำ','หาสาเหตุโดยรักษาข้อมูลและประวัติ'),
            ('ติดตามหลังแก้','ตรวจผลรับรอง การซ่อนค่า และ audit อีกครั้ง บันทึกสาเหตุและการป้องกัน','จบเหตุพร้อมหลักฐาน')],
            note='manifest จากการสำรองระบุ restore_tested:false เครื่องมือนี้ไม่มี scheduler หรือคำสั่ง restore อัตโนมัติ และคู่มือไม่ยืนยันว่าฐานจริงถูกกู้คืนแล้ว'),
        limitations(),
        section('references','แหล่งอ้างอิงภายในและการบำรุงคู่มือ',[
            'นิยามระบบ: docs/source/EdPEx_System_Blueprint_v1.md และ docs/source/EdPEx_6_Instruments.md; การใช้งานจริงให้ตรวจโค้ดและ tests ของรุ่นที่ติดตั้งร่วมด้วย',
            'สิทธิ์: apps/accounts/permissions.py; โครงหน้าและ route: edpex/urls.py; สูตรและผล: apps/calculations/engine.py, codec.py, review.py; สัญญา API: docs/f06-api.openapi.json',
            'สถานะงาน: docs/system-readiness-th.md; รายงานคุณภาพ: docs/nexora-quality-review-th.md; การเก็บ PDF: docs/manuals/manifest.json',
            'อัปเดตคู่มือเมื่อเปลี่ยน route, permission, state transition, field หรือสูตร ระบุรุ่นเอกสารและ source baseline แล้วทดสอบลิงก์และการดาวน์โหลดทุกเล่มอีกครั้ง'])]
    return manual('developer','คู่มือผู้พัฒนาและผู้ดูแลเทคนิค','นักพัฒนา ผู้ติดตั้ง และผู้ดูแลระบบเทคนิค',
        'โครงสร้างเว็บ โมเดลข้อมูล Workflow สิทธิ์ API การทดสอบ การสร้างคู่มือ และการติดตั้ง',sections,category='developer')
