# Generated by Django 5.2.17 on 2026-09-16 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rounds', '0003_population_locking_and_retired_bindings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SurveyProfile',
            fields=[
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='survey_profile', serialize=False, to='rounds.roundinstrument')),
                ('group_code', models.CharField(max_length=80)),
                ('counting_unit', models.CharField(default='person', max_length=40)),
                ('context_th', models.CharField(max_length=500)),
                ('context_en', models.CharField(max_length=500)),
                ('assessor_role', models.CharField(blank=True, max_length=2)),
                ('study_options', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('spent', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(default=False)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_invitations', to='rounds.roundinstrument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.populationmember')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('draft', models.JSONField(default=dict)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveys.invitation')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AnonymousResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=80)),
                ('answers', models.JSONField()),
                ('completion', models.CharField(choices=[('complete', 'complete'), ('partial', 'partial'), ('unable_to_assess', 'unable_to_assess')], max_length=24)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='rounds.roundinstrument')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('completion__in', ['complete', 'partial', 'unable_to_assess'])), name='survey_completion_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('binding', 'member'), name='survey_one_invitation_per_unit'),
        ),
    ]
