# Generated by Django 5.2.17 on 2026-09-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
        ('rounds', '0003_population_locking_and_retired_bindings'),
        ('surveys', '0002_store_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyprofile',
            name='annual_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_profiles', to='leadership.annualtarget'),
        ),
        migrations.AlterField(
            model_name='surveyprofile',
            name='context_en',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='surveyprofile',
            name='context_th',
            field=models.CharField(max_length=1200),
        ),
        migrations.AddConstraint(
            model_name='surveyprofile',
            constraint=models.UniqueConstraint(fields=('annual_target', 'group_code'), name='f04_target_group_collection'),
        ),
    ]
