# Generated by Django 5.2.17 on 2026-09-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_register_guards'),
        ('rounds', '0004_collection_data_kind'),
        ('surveys', '0004_f04_target_guards'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyprofile',
            name='f04_target_group_collection',
        ),
        migrations.AddField(
            model_name='surveyprofile',
            name='intake_method',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('public', 'Public')], default='invitation', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='surveyprofile',
            constraint=models.UniqueConstraint(fields=('annual_target', 'group_code', 'intake_method'), name='f04_target_group_intake'),
        ),
    ]
