# Generated by Django 5.2.17 on 2026-09-15 03:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('calendar_type', models.CharField(choices=[('fiscal', 'ปีงบประมาณ'), ('academic', 'ปีการศึกษา'), ('calendar', 'ปีปฏิทิน'), ('custom', 'กำหนดเอง')], max_length=12)),
                ('timezone', models.CharField(default='Asia/Bangkok', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('open_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('close_at', models.DateTimeField(help_text='Exclusive collection cutoff')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('ready', 'พร้อมเปิด'), ('open', 'เปิดรับ'), ('closed', 'ปิดรับ'), ('calculating', 'คำนวณ'), ('review', 'ตรวจผล'), ('approved', 'รับรองผล'), ('archived', 'เก็บประวัติ')], default='draft', max_length=12)),
                ('privacy_notice', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_collection_rounds', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('location', models.TextField(help_text='Actual report/page, restricted reference, or source URL')),
                ('source_type', models.CharField(choices=[('raw', 'ข้อมูลรายรายการ'), ('aggregate', 'ผลรวมเดิม')], max_length=12)),
                ('original_method', models.CharField(blank=True, max_length=160, null=True)),
                ('instrument_version_original', models.CharField(blank=True, max_length=80, null=True)),
                ('formula_version_original', models.CharField(blank=True, max_length=80, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-fA-F0-9]{64}$', 'Enter an actual SHA-256 digest.')])),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('limitations', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='rounds.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.TextField()),
                ('counting_unit', models.CharField(max_length=80)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='population_snapshots', to='rounds.datasource')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('frozen', 'ตรึงแล้ว')], default='draft', max_length=8)),
                ('counts_by_group', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('collection_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_snapshots', to='rounds.collectionround')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='collectionround',
            name='population_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinned_by_rounds', to='rounds.populationsnapshot'),
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('reporting_year_be', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2565)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Exclusive Gregorian end date')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='rounds.calendar')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='rounds.reportingperiod')),
            ],
        ),
        migrations.AddField(
            model_name='collectionround',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_rounds', to='rounds.reportingperiod'),
        ),
        migrations.CreateModel(
            name='RespondentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='rounds.respondentgroup')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_unit_key', models.CharField(max_length=160)),
                ('employment_facts', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='rounds.populationsnapshot')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='rounds.respondentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibilityAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField(blank=True, help_text='Exclusive end', null=True)),
                ('reason', models.TextField(blank=True)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('collection_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsibilities', to='rounds.collectionround')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='RoundInstrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(default='default', max_length=160)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('collection_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_instruments', to='rounds.collectionround')),
                ('instrument_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.instrumentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('translation_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.translationbundle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='round_calendar_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='round_source_positive_revision'),
        ),
        migrations.AddConstraint(
            model_name='populationsnapshot',
            constraint=models.UniqueConstraint(fields=('collection_round', 'version'), name='round_population_version'),
        ),
        migrations.AddConstraint(
            model_name='populationsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='round_population_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='populationsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frozen_at__isnull', True), ('status', 'draft')), models.Q(('frozen_at__isnull', False), ('status', 'frozen')), _connector='OR'), name='round_population_frozen_time'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(fields=('calendar', 'code', 'version'), name='round_period_code_version'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('reporting_year_be__gte', 2565)), name='round_period_year_2565'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='round_period_positive_window'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='round_period_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved', False), ('approved_at__isnull', True), ('approved_by__isnull', True)), models.Q(('approved', True), ('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='round_period_approval_actor'),
        ),
        migrations.AddConstraint(
            model_name='collectionround',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='round_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='collectionround',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__gte', models.F('open_at')), ('close_at__gte', models.F('due_at')), ('close_at__gt', models.F('open_at'))), name='round_collection_time_order'),
        ),
        migrations.AddConstraint(
            model_name='respondentgroup',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='round_group_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='populationmember',
            constraint=models.UniqueConstraint(fields=('snapshot', 'group', 'eligible_unit_key'), name='round_population_member_unit'),
        ),
        migrations.AddConstraint(
            model_name='responsibilityassignment',
            constraint=models.CheckConstraint(condition=models.Q(('active_until__isnull', True), ('active_until__gt', models.F('active_from')), _connector='OR'), name='round_responsibility_date_order'),
        ),
        migrations.AddConstraint(
            model_name='responsibilityassignment',
            constraint=models.CheckConstraint(condition=models.Q(('backup__isnull', True), models.Q(('primary', models.F('backup')), _negated=True), _connector='OR'), name='round_responsibility_distinct'),
        ),
        migrations.AddConstraint(
            model_name='roundinstrument',
            constraint=models.UniqueConstraint(fields=('collection_round', 'instrument_version', 'context'), name='round_instrument_context'),
        ),
    ]
