# Generated by Django 5.2.17 on 2026-09-15 03:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(choices=[('SAT_TOP2', 'SAT_TOP2'), ('DIS_YES', 'DIS_YES'), ('MEAN_5', 'MEAN_5'), ('ENG_3', 'ENG_3'), ('PAIR_MEAN_TOP', 'PAIR_MEAN_TOP'), ('HAPPINESS_10', 'HAPPINESS_10'), ('DIMENSION_SAT', 'DIMENSION_SAT'), ('ADMIN_MEAN', 'ADMIN_MEAN'), ('ETHICS_TOP', 'ETHICS_TOP'), ('K_EXTERNAL', 'K_EXTERNAL'), ('SELF_VISION', 'SELF_VISION'), ('SELF_VALUES', 'SELF_VALUES'), ('SELF_BEHAVIOUR', 'SELF_BEHAVIOUR'), ('SELF_COMPETENCY', 'SELF_COMPETENCY'), ('SELF_DIMENSION', 'SELF_DIMENSION'), ('SELF_DIGITAL_POP', 'SELF_DIGITAL_POP'), ('TRAINING_HOURS', 'TRAINING_HOURS'), ('TRAINING_PEOPLE', 'TRAINING_PEOPLE'), ('SAFETY_ANY', 'SAFETY_ANY'), ('STUDY_VISIT', 'STUDY_VISIT')], max_length=32)),
                ('version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('retired', 'retired')], default='draft', max_length=12)),
                ('definition_th', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(max_length=64)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=20)),
                ('original_name', models.TextField(blank=True, null=True)),
                ('original_name_status', models.CharField(max_length=100)),
                ('display_name_th', models.TextField()),
                ('display_name_status', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=30)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_rules', models.JSONField(blank=True, default=dict)),
                ('dimensions', models.JSONField(blank=True, default=list)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('indicator_snapshot', models.JSONField(blank=True, default=dict)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='catalog.formulaversion')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='catalog.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='BindingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.indicatorbinding')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(choices=[('F01', 'F01'), ('F02', 'F02'), ('F03', 'F03'), ('F04', 'F04'), ('F05', 'F05'), ('F06', 'F06')], max_length=3)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('retired', 'retired')], default='draft', max_length=12)),
                ('title_th', models.TextField()),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('assessment_method', models.CharField(choices=[('survey', 'survey'), ('verified_activity', 'verified_activity'), ('self_report', 'self_report')], max_length=24)),
                ('evidence_required', models.BooleanField(default=False)),
                ('assessor_scoring', models.BooleanField(default=False)),
                ('response_unit', models.CharField(blank=True, max_length=200)),
                ('identity_domain', models.CharField(blank=True, max_length=100)),
                ('group_codes', models.JSONField(blank=True, default=list)),
                ('workflow', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('instructions_curated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.instrumentversion')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_key', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('instruction', 'instruction'), ('rubric', 'rubric'), ('title', 'title'), ('source_section', 'source_section'), ('ancillary', 'ancillary')], max_length=24)),
                ('text_th', models.TextField()),
                ('audience', models.CharField(default='configuration_only', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='catalog.instrumentversion')),
            ],
        ),
        migrations.AddField(
            model_name='indicatorbinding',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='catalog.instrumentversion'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^F0[1-6]-[A-Z0-9-]+$')])),
                ('text_th', models.TextField()),
                ('answer_type', models.CharField(choices=[('context_reference', 'context_reference'), ('date', 'date'), ('date_time_range', 'date_time_range'), ('decimal', 'decimal'), ('evidence_reference', 'evidence_reference'), ('integer_scale', 'integer_scale'), ('multi_choice', 'multi_choice'), ('review_metadata', 'review_metadata'), ('single_choice', 'single_choice'), ('text', 'text')], max_length=30)),
                ('required_rule', models.JSONField(blank=True, default=dict)),
                ('visibility_rule', models.JSONField(blank=True, default=dict)),
                ('scale', models.JSONField(blank=True, default=dict)),
                ('group_codes', models.JSONField(blank=True, default=list)),
                ('answer_statuses', models.JSONField(blank=True, default=list)),
                ('audience', models.CharField(default='respondent', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.instrumentversion')),
            ],
        ),
        migrations.AddField(
            model_name='indicatorbinding',
            name='questions',
            field=models.ManyToManyField(related_name='bindings', through='catalog.BindingQuestion', to='catalog.question'),
        ),
        migrations.AddField(
            model_name='bindingquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.question'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=80)),
                ('label_th', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('answer_status', models.CharField(default='answered', max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='catalog.question')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bundle_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('retired', 'retired')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('instrument_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_bundles', to='catalog.instrumentversion')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_key', models.CharField(max_length=160)),
                ('locale', models.CharField(choices=[('th', 'ไทย'), ('en', 'English')], max_length=2)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('needs_review', 'needs_review'), ('approved', 'approved'), ('stale', 'stale')], default='draft', max_length=16)),
                ('source_hash', models.CharField(max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='catalog.translationbundle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formulaversion',
            constraint=models.UniqueConstraint(fields=('scope', 'key', 'version'), name='catalog_formula_version'),
        ),
        migrations.AddConstraint(
            model_name='formulaversion',
            constraint=models.CheckConstraint(condition=models.Q(('key__in', ('SAT_TOP2', 'DIS_YES', 'MEAN_5', 'ENG_3', 'PAIR_MEAN_TOP', 'HAPPINESS_10', 'DIMENSION_SAT', 'ADMIN_MEAN', 'ETHICS_TOP', 'K_EXTERNAL', 'SELF_VISION', 'SELF_VALUES', 'SELF_BEHAVIOUR', 'SELF_COMPETENCY', 'SELF_DIMENSION', 'SELF_DIGITAL_POP', 'TRAINING_HOURS', 'TRAINING_PEOPLE', 'SAFETY_ANY', 'STUDY_VISIT'))), name='catalog_formula_allowlist'),
        ),
        migrations.AddConstraint(
            model_name='formulaversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'retired'])), name='catalog_formula_status'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='catalog_indicator_stable_code'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='catalog_instrument_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.CheckConstraint(condition=models.Q(('code__in', ['F01', 'F02', 'F03', 'F04', 'F05', 'F06'])), name='catalog_instrument_code'),
        ),
        migrations.AddConstraint(
            model_name='instrumentversion',
            constraint=models.UniqueConstraint(fields=('instrument', 'version'), name='catalog_instrument_version'),
        ),
        migrations.AddConstraint(
            model_name='instrumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'retired'])), name='catalog_version_status'),
        ),
        migrations.AddConstraint(
            model_name='instrumentcontent',
            constraint=models.UniqueConstraint(fields=('version', 'content_key'), name='catalog_content_stable_key'),
        ),
        migrations.AddConstraint(
            model_name='instrumentcontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'source_section'), _negated=True), ('audience', 'configuration_only'), _connector='OR'), name='catalog_raw_sections_private'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('version', 'question_id'), name='catalog_question_stable_id'),
        ),
        migrations.AddConstraint(
            model_name='indicatorbinding',
            constraint=models.UniqueConstraint(fields=('version', 'indicator'), name='catalog_indicator_binding_version'),
        ),
        migrations.AddConstraint(
            model_name='bindingquestion',
            constraint=models.UniqueConstraint(fields=('binding', 'question'), name='catalog_binding_question_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'code'), name='catalog_option_stable_code'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.CheckConstraint(condition=models.Q(('answer_status', 'answered'), ('score__isnull', True), _connector='OR'), name='catalog_nonanswer_no_score'),
        ),
        migrations.AddConstraint(
            model_name='translationbundle',
            constraint=models.UniqueConstraint(fields=('instrument_version', 'bundle_version'), name='catalog_translation_bundle_version'),
        ),
        migrations.AddConstraint(
            model_name='translationbundle',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'retired'])), name='catalog_bundle_status'),
        ),
        migrations.AddConstraint(
            model_name='contenttranslation',
            constraint=models.UniqueConstraint(fields=('bundle', 'content_key', 'locale'), name='catalog_translation_key_locale'),
        ),
        migrations.AddConstraint(
            model_name='contenttranslation',
            constraint=models.CheckConstraint(condition=models.Q(('locale__in', ['th', 'en'])), name='catalog_translation_locale'),
        ),
        migrations.AddConstraint(
            model_name='contenttranslation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'needs_review', 'approved', 'stale'])), name='catalog_translation_status'),
        ),
        migrations.AddConstraint(
            model_name='contenttranslation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), models.Q(('text', ''), _negated=True)), _connector='OR'), name='catalog_translation_approved_review'),
        ),
        migrations.CreateModel(
            name='LocalizedLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('namespace', models.CharField(choices=[('ui', 'ui'), ('group', 'group'), ('calendar', 'calendar'), ('indicator', 'indicator'), ('notification', 'notification'), ('export', 'export'), ('validation', 'validation'), ('glossary', 'glossary')], max_length=20)),
                ('key', models.CharField(max_length=160)),
                ('version', models.CharField(max_length=40)),
                ('source_th', models.TextField()),
                ('text_en', models.TextField(blank=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('needs_review', 'needs_review'), ('approved', 'approved'), ('stale', 'stale')], default='draft', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accessscope')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'namespace', 'key', 'version'), name='catalog_label_key_version'), models.CheckConstraint(condition=models.Q(('namespace__in', ('ui', 'group', 'calendar', 'indicator', 'notification', 'export', 'validation', 'glossary'))), name='catalog_label_namespace'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'needs_review', 'approved', 'stale'])), name='catalog_label_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), models.Q(('text_en', ''), _negated=True)), _connector='OR'), name='catalog_label_reviewed'), models.CheckConstraint(condition=models.Q(('published', False), models.Q(('published_at__isnull', False), ('status', 'approved')), _connector='OR'), name='catalog_label_publication')],
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('answer_type__in', ('context_reference', 'date', 'date_time_range', 'decimal', 'evidence_reference', 'integer_scale', 'multi_choice', 'review_metadata', 'single_choice', 'text'))), name='catalog_question_type_allowlist'),
        ),
    ]
