# Generated by Django 5.2.17 on 2026-09-15 21:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rounds', '0003_population_locking_and_retired_bindings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessmentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duties', models.TextField()),
                ('expected_levels', models.JSONField()),
                ('applicable_question_ids', models.JSONField()),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.populationmember')),
                ('round_instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rounds.roundinstrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self_assessment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SelfAssessmentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted')], max_length=12)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('completeness', models.CharField(choices=[('partial', 'partial'), ('complete', 'complete')], max_length=12)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a SHA-256 digest.')])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='selfassessments.selfassessmentassignment')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='selfassessmentassignment',
            constraint=models.UniqueConstraint(fields=('round_instrument', 'member'), name='self_assignment_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='selfassessmentassignment',
            constraint=models.UniqueConstraint(fields=('round_instrument', 'user'), name='self_assignment_owner_unique'),
        ),
        migrations.AddConstraint(
            model_name='selfassessmentrevision',
            constraint=models.UniqueConstraint(fields=('assignment', 'revision'), name='self_revision_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='selfassessmentrevision',
            constraint=models.UniqueConstraint(fields=('assignment', 'idempotency_key'), name='self_revision_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='selfassessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='self_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='selfassessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted'])), name='self_revision_state'),
        ),
    ]
